### ISSUE TITLE
怎么创建通知呢？

### ISSUE THREAD

**Issue by XIONGJUNHAN** [n0raml/rsschan#1]
怎么创建通知呢？

**Comment by XIONGJUNHAN** [comment]
我要用push酱，设置了密码，但是现在没有推送

**Comment by XIONGJUNHAN** [comment]
怎么设置呢？

**Comment by n0raml** [comment]
> 我要用push酱，设置了密码，但是现在没有推送

secret里创建PUSH_KEY 填入

**Comment by XIONGJUNHAN** [comment]
和USEREMAILUSERNAME一样？

**Comment by n0raml** [comment]
> 和USEREMAILUSERNAME一样？

是的

**Comment by XIONGJUNHAN** [comment]
notify.py这个文件不用动吧？

**Comment by n0raml** [comment]
> notify.py这个文件不用动吧？

是的，只需要添加变量，

**Comment by XIONGJUNHAN** [comment]
我添加了，目前好像没有通知

**Comment by n0raml** [comment]
> 我添加了，目前好像没有通知

添加完需要有新文章更新才会有通知，在自己的仓库点一个star即可运行更新

**Comment by XIONGJUNHAN** [comment]
好的，我点了

**Comment by XIONGJUNHAN** [comment]
这个rss时延是怎么样的呢？

**Comment by n0raml** [comment]
> 这个rss时延是怎么样的呢？

自动任务每五分钟更新一次，基本可以做到及时。一条一条推送的。push酱可能不支持超链接。蓝字跳转。

**Comment by XIONGJUNHAN** [comment]
哪种推送方式比较好呢？

**Comment by XIONGJUNHAN** [comment]
好的，企业微信的话，就是直接更新secret就好了？

**Comment by n0raml** [comment]
> 好的，企业微信的话，就是直接更新secret就好了？

只留一种通知方式

**Comment by XIONGJUNHAN** [comment]
嗯嗯，那我就删除push酱的secret，然后新建一个企业微信的secret吗？

**Comment by n0raml** [comment]
> 嗯嗯，那我就删除push酱的secret，然后新建一个企业微信的secret吗？

是的 https://www.cnblogs.com/uwiu/
