### ISSUE TITLE
关于安全性的问题

### ISSUE THREAD

**Issue by chenyue404** [n0raml/rsschan#4]
各个推送渠道的密钥都卸载配置文件里，谁都可以看到，是不是不安全啊。
fork的项目又不能设置成私有。
应该怎么处理才好呢？

**Comment by n0raml** [comment]
无需担心，配置文件中是app密钥，那些早已公开。需要隐藏的信息在settings - New repository secret。这些信息不会被公开

**Comment by chenyue404** [comment]
比如[这里](https://github.com/chenyue404/rsschan/blob/3f585c021708dff298b4b054b88c61134e0a199f/notify.py#L77)，要填TG_BOT_TOKEN和TG_USER_ID，那别人不是可以任意调用我的bot了吗？

**Comment by n0raml** [comment]
并不是要求你在notify.py中填入，action会自动获取secret中的变量。所以，你只需要settings - New repository secret添加就可以了。notify.py中不需要你填任何东西
